import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider"



export const metadata: Metadata = {
  title: "Tools list",
  description: "Generated by Axcelion AI",
};

export default function WebillingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div className="flex flex-col">
      <div className="topbar fixed top-0 left-0 right-0 z-50 flex items-center justify-between p-4 bg-black text-primary-foreground">
        <div className="logo flex items-center gap-2">
          <img src="/icon512_rounded.png" alt="Logo" className="h-8 w-8" />
          <span className="text-lg font-bold text-white">Metro billing</span>
        </div>
      </div>
      <div className="flex flex-row flex-wrap gap-2 fixed top-10">
        {children}
      </div>
    </div>
  );
}
